# Generated by Django 3.2.25 on 2024-03-08 03:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
