# Generated by Django 3.2.25 on 2024-03-08 03:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='El año debe ser mayor o igual a 1900.'), django.core.validators.MaxValueValidator(2100, message='El año debe ser menor o igual a 2100.')])),
                ('url_img', models.CharField(blank=True, max_length=50, null=True)),
                ('resumen', models.CharField(blank=True, max_length=150, null=True)),
                ('carroceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.carroceria')),
                ('partes', models.ManyToManyField(blank=True, null=True, to='modelos.Parte')),
            ],
        ),
    ]
