# Generated by Django 3.2.25 on 2024-03-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='partes',
            field=models.ManyToManyField(blank=True, to='modelos.Parte'),
        ),
    ]
