# Generated by Django 3.2.25 on 2024-03-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_alter_modelo_partes'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.CharField(default='', max_length=50),
        ),
    ]
