# Generated by Django 3.2.25 on 2024-03-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_modelo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
    ]
